apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: nginx-ingress-servicemonitor
  name: nginx-ingress-servicemonitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: metrics
  selector:
    matchLabels:
            app: ingress-nginx
  namespaceSelector:
    matchNames:
    - ingress-nginx
